import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../../kit.config";
import { loadSettings } from "@webicient/sanity-kit/query";
import { SiteProvider } from "@/components/SiteProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data: settings } = await loadSettings();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SiteProvider settings={settings}>{children}</SiteProvider>
      </body>
    </html>
  );
}
